import { listRecords, createRecord, updateRecord, deleteRecord, isFirebaseConfigured } from './firebase.js';
const qs = (selector) => document.querySelector(selector);
let signalData = [];
let userData = [];
const signalMarkup = (item) => `<div class="admin-list-row" data-id="${item.id}"><div><b>${item.asset}</b><small>${item.pair} · ${item.timeframe}</small></div><span class="status-pill">${item.status}</span><span>${item.confidence}%</span><div class="crud-actions"><button data-action="edit">Edit</button><button data-action="delete">Delete</button></div></div>`;
const userMarkup = (item) => `<div class="admin-list-row" data-id="${item.id}"><div><b>${item.name}</b><small>${item.email}</small></div><span>${item.role}</span><span class="status-pill">${item.status}</span><div class="crud-actions"><button data-action="edit">Edit</button><button data-action="delete">Delete</button></div></div>`;
async function render() { signalData = await listRecords('signals'); userData = await listRecords('users'); qs('#signals-list').innerHTML = signalData.map(signalMarkup).join('') || '<div class="empty-state">No signals yet.</div>'; qs('#users-list').innerHTML = userData.map(userMarkup).join('') || '<div class="empty-state">No members yet.</div>'; qs('#signal-count').textContent = signalData.filter((item) => item.status === 'Active').length; qs('#member-count').textContent = userData.length; bindRows(); }
async function mutate(collection, id, action) { if (action === 'delete') { if (!confirm('Delete this record?')) return; await deleteRecord(collection, id); } if (action === 'edit') { const source = (collection === 'signals' ? signalData : userData).find((item) => item.id === id); const value = prompt(`Update ${collection === 'signals' ? 'confidence' : 'role'}:`, collection === 'signals' ? source.confidence : source.role); if (value === null) return; await updateRecord(collection, id, collection === 'signals' ? { confidence: Number(value) || source.confidence } : { role: value }); } await render(); }
function bindRows() { document.querySelectorAll('[data-action]').forEach((button) => button.addEventListener('click', () => { const row = button.closest('[data-id]'); mutate(row.parentElement.id === 'signals-list' ? 'signals' : 'users', row.dataset.id, button.dataset.action); })); }
qs('#add-signal')?.addEventListener('click', async () => { const asset = prompt('Asset name:', 'Solana'); if (!asset) return; await createRecord('signals', { asset, pair: `${asset} / USD`, direction: 'Long', confidence: 78, timeframe: '4H', status: 'Active' }); await render(); });
qs('#refresh-users')?.addEventListener('click', render);
render();
if (!isFirebaseConfigured()) { const note = document.createElement('div'); note.className = 'auth-note'; note.textContent = 'Preview data is in memory only. Add Firebase credentials in js/firebase.js to persist CRUD operations in Firestore.'; qs('.admin-main').append(note); }
